package view;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import javax.swing.SwingUtilities;


public class Main extends javax.swing.JFrame {

    private Login login;
    private Register register;
 
    
   public void setLogin(){
        if(login == null){
            login = new Login(this);
        }
          BLogin.setBackground(new Color(77,120,204));
          BRegister.setBackground(new Color(44,44,44));
        
        jPanel2.removeAll();
        jPanel2.add(login);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
   
     public void setRegister(){
        if(register == null){
            register = new Register(this);                   
        }
        BRegister.setBackground(new Color(77,120,204));
         BLogin.setBackground(new Color(44,44,44));
        jPanel2.removeAll();
        jPanel2.add(register);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
     
               
    public Main() {
        initComponents();
        setLogin();
       setLocationRelativeTo(null);
    }
    public void setMenu(){
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BLogin = new javax.swing.JButton();
        BRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 690));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 49));

        BLogin.setBackground(new java.awt.Color(28, 100, 163));
        BLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        BLogin.setForeground(new java.awt.Color(255, 255, 255));
        BLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/enter (1).png"))); // NOI18N
        BLogin.setText("Log in");
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 122, 265, 40));

        BRegister.setBackground(new java.awt.Color(27, 27, 28));
        BRegister.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        BRegister.setForeground(new java.awt.Color(255, 255, 255));
        BRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clipboard-list.png"))); // NOI18N
        BRegister.setText("Register");
        BRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(BRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 191, 265, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sporting Etiquette _ Beyond Sportsmanship - Satsuma Designs.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 350, 680));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
        // TODO add your handling code here:
             
                setLogin();
    }//GEN-LAST:event_BLoginActionPerformed

    private void BRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegisterActionPerformed
        // TODO add your handling code here:
             
                setRegister();
    }//GEN-LAST:event_BRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();
 
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
 public void CallSetLogin(){
     setLogin();
 }
 public void CallSetRegister(){
     setRegister();
 }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BLogin;
    private javax.swing.JButton BRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}